language: python
sudo: false
dist: trusty

python:
  - 2.7
  - 3.5
  - 3.6

cache:
  pip: true

addons:
  apt:
    packages:
      - libopenbabel-dev
      - swig

virtualenv:
      system_site_packages: true

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover tests
