language: python
sudo: false
dist: trusty

python:
  - 2.7
  - 3.5
  - 3.6

cache:
  pip: true

addons:
  apt:
    packages:
      - libopenbabel-dev
      - swig

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover tests
